# Generated by Django 3.0.2 on 2020-04-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techguy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='techguy',
            name='email',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
